# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
    format: zip
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: <github_username>
    name: <repository_name>
  draft: true
  prerelease: auto
  disable: false
