before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

release:
  github:
    owner: PerArneng
    name: srctotext
  draft: true
  prerelease: auto
  disable: false
